name: 'Publish Installers'
on:
  push:
    tags:
      - 'v*'

jobs:
  publish-tauri:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5

      - name: setup node
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Update versions from tag
        run: |
          $version = "${{ github.ref_name }}".TrimStart('v')
          (Get-Content package.json) -replace '"version": "[^"]+"', "`"version`": `"$version`"" | Set-Content package.json
          (Get-Content src-tauri\tauri.conf.json) -replace '"version": "[^"]+"', "`"version`": `"$version`"" | Set-Content src-tauri\tauri.conf.json
          (Get-Content public\manifest.json) -replace '"version": "[^"]+"', "`"version`": `"$version`"" | Set-Content public\manifest.json

      - name: install frontend dependencies
        run: npm install

      - name: Build Chrome Extension
        run: npm run build

      - name: Zip Extension (Windows)
        run: Compress-Archive -Path dist\* -DestinationPath browser-extension.zip

      - name: Build Desktop App
        uses: tauri-apps/tauri-action@v0

      - name: Zip Desktop Apps
        run: |
          Compress-Archive -Path src-tauri\target\release\bundle\nsis\*.exe -DestinationPath otp-authenticator-windows-exe.zip
          Compress-Archive -Path src-tauri\target\release\bundle\msi\*.msi -DestinationPath otp-authenticator-windows-msi.zip

      - name: Upload Assets to Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            browser-extension.zip
            otp-authenticator-windows-exe.zip
            otp-authenticator-windows-msi.zip
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
